export const cardCarousel = [
    {
        id: 1,
        img: "https://img.freepik.com/free-photo/observation-urban-building-business-steel_1127-2397.jpg",
        city: "dubai",
        BuildingName: "TruEstimate™",
        type:"Apartment",
        location: "New York, NY",
        launchPrice: "$1,200,000",
        Handover:"Q1 2025",
    },
    {
        id: 2,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_ljff2QGyXvPEGtZPIDH-Gd_BPDMj1crsxA&s",
        city: "dubai",
        BuildingName: "TruBuilding™",
        type:"Condo",
        location: "Los Angeles, CA",
        launchPrice: "$1,500,000",
        Handover:"Q2 2025",
    },
    {
        id: 3,
        img: "https://i.pinimg.com/736x/e7/d7/45/e7d745cda4e178e5dcb9bf751eb39bbd.jpg",
        city: "dubai",
        BuildingName: "Map View",
        type:"Townhouse",
        location: "Chicago, IL",
        launchPrice: "$900,000",
        Handover:"Q3 2025",
    },
    {
        id: 4,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQH-HcfRUFeQtlVMptwCwLaqag_YDdEHK9XWw&s",
        city: "dubai",
        BuildingName: "Map View",
        type:"Townhouse",
        location: "Chicago, IL",
        launchPrice: "$900,000",
        Handover:"Q3 2025",
    },
    {
        id: 5,
        img: "https://thumbs.dreamstime.com/b/modern-residential-building-beautiful-recreation-area-modern-residential-building-recreation-area-131403554.jpg",
        city: "dubai",
        BuildingName: "Map View",
        type:"Townhouse",
        location: "Chicago, IL",
        launchPrice: "$900,000",
        Handover:"Q3 2025",
    },
    {
        id: 6,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-QXXScrq4ImcfIuZPcXBLLA8a-CAL5lbTCQ&s",
        city: "dubai",
        BuildingName: "Map View",
        type:"Townhouse",
        location: "Chicago, IL",
        launchPrice: "$900,000",
        Handover:"Q3 2025",
    },

]