export const cardCarousel = [
    {
        id: 1,
        img: "https://img.freepik.com/free-photo/observation-urban-building-business-steel_1127-2397.jpg",
        city: "dubai",
        BuildingName: "TruEstimate™",
        type:"Apartment",
        location: "New York, NY",
        launchPrice: "$1,200,000",
        Handover:"Q1 2025",
    },
    {
        id: 2,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_ljff2QGyXvPEGtZPIDH-Gd_BPDMj1crsxA&s",
        city: "dubai",
        BuildingName: "TruBuilding™",
        type:"Condo",
        location: "Los Angeles, CA",
        launchPrice: "$1,500,000",
        Handover:"Q2 2025",
    },
    {
        id: 3,
        img: "https://i.pinimg.com/736x/e7/d7/45/e7d745cda4e178e5dcb9bf751eb39bbd.jpg",
        city: "dubai",
        BuildingName: "Map View",
        type:"Townhouse",
        location: "Chicago, IL",
        launchPrice: "$900,000",
        Handover:"Q3 2025",
    },
    {
        id: 4,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQH-HcfRUFeQtlVMptwCwLaqag_YDdEHK9XWw&s",
        city: "dubai",
        BuildingName: "Map View",
        type:"Townhouse",
        location: "Chicago, IL",
        launchPrice: "$900,000",
        Handover:"Q3 2025",
    },
    {
        id: 5,
        img: "https://thumbs.dreamstime.com/b/modern-residential-building-beautiful-recreation-area-modern-residential-building-recreation-area-131403554.jpg",
        city: "dubai",
        BuildingName: "Map View",
        type:"Townhouse",
        location: "Chicago, IL",
        launchPrice: "$900,000",
        Handover:"Q3 2025",
    },
    {
        id: 6,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-QXXScrq4ImcfIuZPcXBLLA8a-CAL5lbTCQ&s",
        city: "dubai",
        BuildingName: "Map View",
        type:"Townhouse",
        location: "Chicago, IL",
        launchPrice: "$900,000",
        Handover:"Q3 2025",
    },

]

export const cardData = [
    {
        id: 1,
        price:"5,200,000",
        bed:"4",
        bath:"3",
        type:"Villa",
        area:"3,000 sqft",
        location:"Oliva, Victory Heights, Dubai Sports City, Dubai",
        heading:"Open House this Sunday! 10am - 4pm by appointment",
        paragraph:"Welcome to this beautifully maintained TH2 in the sought-after Victory Heights community. Ideally located in the heart of Victory Heights, this 4-bedroom home offers the perfect blend of comfort, space, and privacy — ideal for families seeking an active, community-driven lifestyle.",
        image:[
            "https://images.ctfassets.net/pg6xj64qk0kh/2r4QaBLvhQFH1mPGljSdR9/39b737d93854060282f6b4a9b9893202/camden-paces-apartments-buckhead-ga-terraces-living-room-with-den_1.jpg",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX9PiX8SL3QGE2MksnHs0rKJinqe38Izpa9g&s",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_ljff2QGyXvPEGtZPIDH-Gd_BPDMj1crsxA&s",
            "https://media.istockphoto.com/id/1398814566/photo/interior-of-small-apartment-living-room-for-home-office.jpg?s=612x612&w=0&k=20&c=8clwg8hTpvoEwL7253aKdYAUuAp1-usFOacNR5qX-Rg=",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpzI3qfOoXsgu73u-NNGt_BXALrPxV2K19Pg&s",
        ]
    },
    {
        id: 1,
        price:"5,200,000",
        bed:"4",
        bath:"3",
        type:"Villa",
        area:"3,000 sqft",
        location:"Oliva, Victory Heights, Dubai Sports City, Dubai",
        heading:"Open House this Sunday! 10am - 4pm by appointment",
        paragraph:"Welcome to this beautifully maintained TH2 in the sought-after Victory Heights community. Ideally located in the heart of Victory Heights, this 4-bedroom home offers the perfect blend of comfort, space, and privacy — ideal for families seeking an active, community-driven lifestyle.",
        image:[
            "https://images.ctfassets.net/pg6xj64qk0kh/2r4QaBLvhQFH1mPGljSdR9/39b737d93854060282f6b4a9b9893202/camden-paces-apartments-buckhead-ga-terraces-living-room-with-den_1.jpg",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX9PiX8SL3QGE2MksnHs0rKJinqe38Izpa9g&s",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_ljff2QGyXvPEGtZPIDH-Gd_BPDMj1crsxA&s",
            "https://media.istockphoto.com/id/1398814566/photo/interior-of-small-apartment-living-room-for-home-office.jpg?s=612x612&w=0&k=20&c=8clwg8hTpvoEwL7253aKdYAUuAp1-usFOacNR5qX-Rg=",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpzI3qfOoXsgu73u-NNGt_BXALrPxV2K19Pg&s",
        ]
    },
    {
        id: 1,
        price:"5,200,000",
        bed:"4",
        bath:"3",
        type:"Villa",
        area:"3,000 sqft",
        location:"Oliva, Victory Heights, Dubai Sports City, Dubai",
        heading:"Open House this Sunday! 10am - 4pm by appointment",
        paragraph:"Welcome to this beautifully maintained TH2 in the sought-after Victory Heights community. Ideally located in the heart of Victory Heights, this 4-bedroom home offers the perfect blend of comfort, space, and privacy — ideal for families seeking an active, community-driven lifestyle.",
        image:[
            "https://images.ctfassets.net/pg6xj64qk0kh/2r4QaBLvhQFH1mPGljSdR9/39b737d93854060282f6b4a9b9893202/camden-paces-apartments-buckhead-ga-terraces-living-room-with-den_1.jpg",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX9PiX8SL3QGE2MksnHs0rKJinqe38Izpa9g&s",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_ljff2QGyXvPEGtZPIDH-Gd_BPDMj1crsxA&s",
            "https://media.istockphoto.com/id/1398814566/photo/interior-of-small-apartment-living-room-for-home-office.jpg?s=612x612&w=0&k=20&c=8clwg8hTpvoEwL7253aKdYAUuAp1-usFOacNR5qX-Rg=",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpzI3qfOoXsgu73u-NNGt_BXALrPxV2K19Pg&s",
        ]
    },
    {
        id: 1,
        price:"5,200,000",
        bed:"4",
        bath:"3",
        type:"Villa",
        area:"3,000 sqft",
        location:"Oliva, Victory Heights, Dubai Sports City, Dubai",
        heading:"Open House this Sunday! 10am - 4pm by appointment",
        paragraph:"Welcome to this beautifully maintained TH2 in the sought-after Victory Heights community. Ideally located in the heart of Victory Heights, this 4-bedroom home offers the perfect blend of comfort, space, and privacy — ideal for families seeking an active, community-driven lifestyle.",
        image:[
            "https://images.ctfassets.net/pg6xj64qk0kh/2r4QaBLvhQFH1mPGljSdR9/39b737d93854060282f6b4a9b9893202/camden-paces-apartments-buckhead-ga-terraces-living-room-with-den_1.jpg",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX9PiX8SL3QGE2MksnHs0rKJinqe38Izpa9g&s",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_ljff2QGyXvPEGtZPIDH-Gd_BPDMj1crsxA&s",
            "https://media.istockphoto.com/id/1398814566/photo/interior-of-small-apartment-living-room-for-home-office.jpg?s=612x612&w=0&k=20&c=8clwg8hTpvoEwL7253aKdYAUuAp1-usFOacNR5qX-Rg=",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpzI3qfOoXsgu73u-NNGt_BXALrPxV2K19Pg&s",
        ]
    },
    {
        id: 1,
        price:"5,200,000",
        bed:"4",
        bath:"3",
        type:"Villa",
        area:"3,000 sqft",
        location:"Oliva, Victory Heights, Dubai Sports City, Dubai",
        heading:"Open House this Sunday! 10am - 4pm by appointment",
        paragraph:"Welcome to this beautifully maintained TH2 in the sought-after Victory Heights community. Ideally located in the heart of Victory Heights, this 4-bedroom home offers the perfect blend of comfort, space, and privacy — ideal for families seeking an active, community-driven lifestyle.",
        image:[
            "https://images.ctfassets.net/pg6xj64qk0kh/2r4QaBLvhQFH1mPGljSdR9/39b737d93854060282f6b4a9b9893202/camden-paces-apartments-buckhead-ga-terraces-living-room-with-den_1.jpg",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX9PiX8SL3QGE2MksnHs0rKJinqe38Izpa9g&s",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_ljff2QGyXvPEGtZPIDH-Gd_BPDMj1crsxA&s",
            "https://media.istockphoto.com/id/1398814566/photo/interior-of-small-apartment-living-room-for-home-office.jpg?s=612x612&w=0&k=20&c=8clwg8hTpvoEwL7253aKdYAUuAp1-usFOacNR5qX-Rg=",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpzI3qfOoXsgu73u-NNGt_BXALrPxV2K19Pg&s",
        ]
    },
    {
        id: 1,
        price:"5,200,000",
        bed:"4",
        bath:"3",
        type:"Villa",
        area:"3,000 sqft",
        location:"Oliva, Victory Heights, Dubai Sports City, Dubai",
        heading:"Open House this Sunday! 10am - 4pm by appointment",
        paragraph:"Welcome to this beautifully maintained TH2 in the sought-after Victory Heights community. Ideally located in the heart of Victory Heights, this 4-bedroom home offers the perfect blend of comfort, space, and privacy — ideal for families seeking an active, community-driven lifestyle.",
        image:[
            "https://images.ctfassets.net/pg6xj64qk0kh/2r4QaBLvhQFH1mPGljSdR9/39b737d93854060282f6b4a9b9893202/camden-paces-apartments-buckhead-ga-terraces-living-room-with-den_1.jpg",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX9PiX8SL3QGE2MksnHs0rKJinqe38Izpa9g&s",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_ljff2QGyXvPEGtZPIDH-Gd_BPDMj1crsxA&s",
            "https://media.istockphoto.com/id/1398814566/photo/interior-of-small-apartment-living-room-for-home-office.jpg?s=612x612&w=0&k=20&c=8clwg8hTpvoEwL7253aKdYAUuAp1-usFOacNR5qX-Rg=",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpzI3qfOoXsgu73u-NNGt_BXALrPxV2K19Pg&s",
        ]
    },
    {
        id: 1,
        price:"5,200,000",
        bed:"4",
        bath:"3",
        type:"Villa",
        area:"3,000 sqft",
        location:"Oliva, Victory Heights, Dubai Sports City, Dubai",
        heading:"Open House this Sunday! 10am - 4pm by appointment",
        paragraph:"Welcome to this beautifully maintained TH2 in the sought-after Victory Heights community. Ideally located in the heart of Victory Heights, this 4-bedroom home offers the perfect blend of comfort, space, and privacy — ideal for families seeking an active, community-driven lifestyle.",
        image:[
            "https://images.ctfassets.net/pg6xj64qk0kh/2r4QaBLvhQFH1mPGljSdR9/39b737d93854060282f6b4a9b9893202/camden-paces-apartments-buckhead-ga-terraces-living-room-with-den_1.jpg",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX9PiX8SL3QGE2MksnHs0rKJinqe38Izpa9g&s",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_ljff2QGyXvPEGtZPIDH-Gd_BPDMj1crsxA&s",
            "https://media.istockphoto.com/id/1398814566/photo/interior-of-small-apartment-living-room-for-home-office.jpg?s=612x612&w=0&k=20&c=8clwg8hTpvoEwL7253aKdYAUuAp1-usFOacNR5qX-Rg=",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpzI3qfOoXsgu73u-NNGt_BXALrPxV2K19Pg&s",
        ]
    },
    {
        id: 1,
        price:"5,200,000",
        bed:"4",
        bath:"3",
        type:"Villa",
        area:"3,000 sqft",
        location:"Oliva, Victory Heights, Dubai Sports City, Dubai",
        heading:"Open House this Sunday! 10am - 4pm by appointment",
        paragraph:"Welcome to this beautifully maintained TH2 in the sought-after Victory Heights community. Ideally located in the heart of Victory Heights, this 4-bedroom home offers the perfect blend of comfort, space, and privacy — ideal for families seeking an active, community-driven lifestyle.",
        image:[
            "https://images.ctfassets.net/pg6xj64qk0kh/2r4QaBLvhQFH1mPGljSdR9/39b737d93854060282f6b4a9b9893202/camden-paces-apartments-buckhead-ga-terraces-living-room-with-den_1.jpg",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX9PiX8SL3QGE2MksnHs0rKJinqe38Izpa9g&s",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_ljff2QGyXvPEGtZPIDH-Gd_BPDMj1crsxA&s",
            "https://media.istockphoto.com/id/1398814566/photo/interior-of-small-apartment-living-room-for-home-office.jpg?s=612x612&w=0&k=20&c=8clwg8hTpvoEwL7253aKdYAUuAp1-usFOacNR5qX-Rg=",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpzI3qfOoXsgu73u-NNGt_BXALrPxV2K19Pg&s",
        ]
    },
    {
        id: 1,
        price:"5,200,000",
        bed:"4",
        bath:"3",
        type:"Villa",
        area:"3,000 sqft",
        location:"Oliva, Victory Heights, Dubai Sports City, Dubai",
        heading:"Open House this Sunday! 10am - 4pm by appointment",
        paragraph:"Welcome to this beautifully maintained TH2 in the sought-after Victory Heights community. Ideally located in the heart of Victory Heights, this 4-bedroom home offers the perfect blend of comfort, space, and privacy — ideal for families seeking an active, community-driven lifestyle.",
        image:[
            "https://images.ctfassets.net/pg6xj64qk0kh/2r4QaBLvhQFH1mPGljSdR9/39b737d93854060282f6b4a9b9893202/camden-paces-apartments-buckhead-ga-terraces-living-room-with-den_1.jpg",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX9PiX8SL3QGE2MksnHs0rKJinqe38Izpa9g&s",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_ljff2QGyXvPEGtZPIDH-Gd_BPDMj1crsxA&s",
            "https://media.istockphoto.com/id/1398814566/photo/interior-of-small-apartment-living-room-for-home-office.jpg?s=612x612&w=0&k=20&c=8clwg8hTpvoEwL7253aKdYAUuAp1-usFOacNR5qX-Rg=",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpzI3qfOoXsgu73u-NNGt_BXALrPxV2K19Pg&s",
        ]
    },
    {
        id: 1,
        price:"5,200,000",
        bed:"4",
        bath:"3",
        type:"Villa",
        area:"3,000 sqft",
        location:"Oliva, Victory Heights, Dubai Sports City, Dubai",
        heading:"Open House this Sunday! 10am - 4pm by appointment",
        paragraph:"Welcome to this beautifully maintained TH2 in the sought-after Victory Heights community. Ideally located in the heart of Victory Heights, this 4-bedroom home offers the perfect blend of comfort, space, and privacy — ideal for families seeking an active, community-driven lifestyle.",
        image:[
            "https://images.ctfassets.net/pg6xj64qk0kh/2r4QaBLvhQFH1mPGljSdR9/39b737d93854060282f6b4a9b9893202/camden-paces-apartments-buckhead-ga-terraces-living-room-with-den_1.jpg",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX9PiX8SL3QGE2MksnHs0rKJinqe38Izpa9g&s",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_ljff2QGyXvPEGtZPIDH-Gd_BPDMj1crsxA&s",
            "https://media.istockphoto.com/id/1398814566/photo/interior-of-small-apartment-living-room-for-home-office.jpg?s=612x612&w=0&k=20&c=8clwg8hTpvoEwL7253aKdYAUuAp1-usFOacNR5qX-Rg=",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpzI3qfOoXsgu73u-NNGt_BXALrPxV2K19Pg&s",
        ]
    },
    {
        id: 1,
        price:"5,200,000",
        bed:"4",
        bath:"3",
        type:"Villa",
        area:"3,000 sqft",
        location:"Oliva, Victory Heights, Dubai Sports City, Dubai",
        heading:"Open House this Sunday! 10am - 4pm by appointment",
        paragraph:"Welcome to this beautifully maintained TH2 in the sought-after Victory Heights community. Ideally located in the heart of Victory Heights, this 4-bedroom home offers the perfect blend of comfort, space, and privacy — ideal for families seeking an active, community-driven lifestyle.",
        image:[
            "https://images.ctfassets.net/pg6xj64qk0kh/2r4QaBLvhQFH1mPGljSdR9/39b737d93854060282f6b4a9b9893202/camden-paces-apartments-buckhead-ga-terraces-living-room-with-den_1.jpg",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX9PiX8SL3QGE2MksnHs0rKJinqe38Izpa9g&s",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_ljff2QGyXvPEGtZPIDH-Gd_BPDMj1crsxA&s",
            "https://media.istockphoto.com/id/1398814566/photo/interior-of-small-apartment-living-room-for-home-office.jpg?s=612x612&w=0&k=20&c=8clwg8hTpvoEwL7253aKdYAUuAp1-usFOacNR5qX-Rg=",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpzI3qfOoXsgu73u-NNGt_BXALrPxV2K19Pg&s",
        ]
    },
    {
        id: 1,
        price:"5,200,000",
        bed:"4",
        bath:"3",
        type:"Villa",
        area:"3,000 sqft",
        location:"Oliva, Victory Heights, Dubai Sports City, Dubai",
        heading:"Open House this Sunday! 10am - 4pm by appointment",
        paragraph:"Welcome to this beautifully maintained TH2 in the sought-after Victory Heights community. Ideally located in the heart of Victory Heights, this 4-bedroom home offers the perfect blend of comfort, space, and privacy — ideal for families seeking an active, community-driven lifestyle.",
        image:[
            "https://images.ctfassets.net/pg6xj64qk0kh/2r4QaBLvhQFH1mPGljSdR9/39b737d93854060282f6b4a9b9893202/camden-paces-apartments-buckhead-ga-terraces-living-room-with-den_1.jpg",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX9PiX8SL3QGE2MksnHs0rKJinqe38Izpa9g&s",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_ljff2QGyXvPEGtZPIDH-Gd_BPDMj1crsxA&s",
            "https://media.istockphoto.com/id/1398814566/photo/interior-of-small-apartment-living-room-for-home-office.jpg?s=612x612&w=0&k=20&c=8clwg8hTpvoEwL7253aKdYAUuAp1-usFOacNR5qX-Rg=",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpzI3qfOoXsgu73u-NNGt_BXALrPxV2K19Pg&s",
        ]
    },
    {
        id: 2,
        price:"5,200,000",
        bed:"4",
        bath:"3",
        type:"Villa",
        area:"3,000 sqft",
        location:"Oliva, Victory Heights, Dubai Sports City, Dubai",
        heading:"Open House this Sunday! 10am - 4pm by appointment",
        paragraph:"Welcome to this beautifully maintained TH2 in the sought-after Victory Heights community. Ideally located in the heart of Victory Heights, this 4-bedroom home offers the perfect blend of comfort, space, and privacy — ideal for families seeking an active, community-driven lifestyle.",
        image:[
            "https://img.freepik.com/free-photo/observation-urban-building-business-steel_1127-2397.jpg",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_ljff2QGyXvPEGtZPIDH-Gd_BPDMj1crsxA&s",
            "https://i.pinimg.com/736x/e7/d7/45/e7d745cda4e178e5dcb9bf751eb39bbd.jpg",
        ]
    },
    {
        id: 3,
        price:"5,200,000",
        bed:"4",
        bath:"3",
        type:"Villa",
        area:"3,000 sqft",
        location:"Oliva, Victory Heights, Dubai Sports City, Dubai",
        heading:"Open House this Sunday! 10am - 4pm by appointment",
        paragraph:"Welcome to this beautifully maintained TH2 in the sought-after Victory Heights community. Ideally located in the heart of Victory Heights, this 4-bedroom home offers the perfect blend of comfort, space, and privacy — ideal for families seeking an active, community-driven lifestyle.",
        image:[
            "https://img.freepik.com/free-photo/observation-urban-building-business-steel_1127-2397.jpg",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_ljff2QGyXvPEGtZPIDH-Gd_BPDMj1crsxA&s",
            "https://i.pinimg.com/736x/e7/d7/45/e7d745cda4e178e5dcb9bf751eb39bbd.jpg",
        ]
    }
]